[project]
name = "ai-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ai-foundations",
    "ipykernel>=7.2.0",
    "ipython>=7.34.0",
    "jax[cuda12]==0.7.2",
    "nbformat>=5.10.4",
    "pip>=26.1",
    "tensorflow>=2.20.0",
]

[tool.uv.sources]
ai-foundations = { git = "https://github.com/google-deepmind/ai-foundations.git", rev = "main" }
